# Generated by Django 4.0.6 on 2022-08-01 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catgegory',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(default='Fish', on_delete=django.db.models.deletion.SET_DEFAULT, to='app_v1.catgegory')),
            ],
        ),
        migrations.CreateModel(
            name='Size_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_price', models.FloatField()),
                ('med_price', models.FloatField()),
                ('big_price', models.FloatField()),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_v1.product')),
            ],
        ),
        migrations.CreateModel(
            name='Prod_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_clean', models.BooleanField(default=True)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_v1.size_price')),
            ],
        ),
    ]
